# Generated by Django 5.1.2 on 2024-11-22 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('rating', models.PositiveSmallIntegerField()),
                ('discount', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=8)),
                ('email', models.CharField(blank=True, max_length=52, null=True)),
                ('koment', models.TextField(blank=True, null=True)),
                ('count', models.PositiveBigIntegerField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
        ),
    ]
