# Generated by Django 5.1.2 on 2024-11-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_product_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='koment',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
