# Generated by Django 5.1.2 on 2024-11-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_email_alter_order_koment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='koment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
